{% set version = "1.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-whoami
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/whoami_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/whoami/whoami_{{ version }}.tar.gz
  sha256: c20bc9259399bfbee21cd46f21c4ce6d8ef078449063febba093e852fea1dca5

build:
  noarch: generic
  number: 6
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-httr
    - r-jsonlite
  run:
    - r-base
    - r-httr
    - r-jsonlite

test:
  commands:
    - $R -e "library('whoami')"           # [not win]
    - "\"%R%\" -e \"library('whoami')\""  # [win]

about:
  home: https://github.com/r-lib/whoami#readme
  license: MIT
  summary: Look up the username and full name of the current user, the current user's email address and 'GitHub' username, using various sources of system and configuration information.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - russHyde
