travis:
  secure:
    BINSTAR_TOKEN: d+IrgaTzajS1nnuFCwAdt1u4jexSBDVqHI+v4vTjEwegG8vKZdX/CVlpAyUiFDvSk2BiWRbFLR9/1n1qCwspJvWv10yMCg/3xuqRZFoyishdrYcmfeeH4syIB7zRSKbIPES959qHV9iHkA86eEb6NIkU9bY6qcKo2vYoFvt5iMLVnoBIA3v2REnuiS6nxAPYzoZTqyn/1ge2zpTzgs3XMJJYhMsy5APq9WT2wvd4MZMnAdDajmtM2eLYokoFyoT7XvFin5CHmEU/86aUSxxjsEHCqNWvTT4xgibVFg0bbzZ60kUzZ15ZD/O/aEBmVcyVuGItFm9C2k7VnKMXSmzfjAdKzUzQkuOtCMEzp+H/nzeDyHUco4dqGk8E3AJ7RSVLm++2Y2AWJiIJHIuwfVUIqGTgVi0LvWmSUfuGiixVsgYljKwD9XlF/qS5WMeg83Blp+CAhureFB+Cvv2URf2Kt/Y5p8/EJaMmUJiL/HrJtQpBbORU2n64HdJWF8SBX8cuI1J92ATK375aLnPH8XsLyHfIckEX9BYXd1nIaLc8osjP7IquCeR0XxEQAPkKrpiRLlbDww15t31wJipFB+5sOnkx7rrjQtsTZPv/0hI+Qi24Zane0gj8jjmgVzdU77WAtLqDbdvs7E6KzIDuZyuaJcjyj78ZYpWdEnjGg5otVFw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
